[project]
name = "nlp-backend"
version = "1.0.0"
description = "sumarizes privacy policy."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"