[project]
name = "proto_flask_controller"
version = "1.0.0"
description = "sumarizes privacy policy."
dependencies = [
    "flask",
    "bert-extractive-summarizer"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"