
# Workflow for automated testing

name: tests

# Runs on push and pull requests
on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Job for testing the back end of the product
  test_back_end:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Test backend with pytest
        run: |
          pip install pytest pytest-cov
          pytest
